networks:
  dreams-shop: 
    driver: bridge
  
volumes:
  shared-data: 
  minio_data:
  
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - shared-data:/usr/share/nginx/html:ro
    depends_on:
      - business
      - identity
      - client
    networks:
      - dreams-shop
  
  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    volumes:
      - shared-data:/output
    networks:
      - dreams-shop

  identity:
    build:
      context: ./Idenitity
      dockerfile: Dockerfile
    ports:
      - 5001:5001
      - 8081:8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - dreams-shop
    depends_on:
      - postgres
  
  business:
    build:
      context: ./Business
      dockerfile: Dockerfile
    ports:
      - 5002:5002
      - 8082:8082
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - dreams-shop
    depends_on:
      - postgres
      - minio
    
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: DreamsShop_Client
      POSTGRES_PASSWORD: M3fFSh99@Gcb932*5fhh
      POSTGRES_DB: DreamsShop_Business
    networks:
      - dreams-shop
  
  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: "%Gt2enf*@fd/sdF"
    command: server /data --console-address :9001
    networks:
      - dreams-shop
    volumes:
      - minio_data:/data

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - dreams-shop